<?php
// $Id: micro_publisher_node.install, v 1.0 2010/12/01 04:20:00 blup Exp $

/**
 * @file
 * Install function for the micro_publisher_node module.
 */

/**
 * Implement hook_install().
 */
function micro_publisher_node_install() {
  micro_types_rebuild();
  _micro_publisher_status('node');
  _micro_publisher_event('node');
  _micro_publisher_image('node');
  _micro_publisher_video('node');
  _micro_publisher_file('node');
}
